trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '*'
    - src/libraries/System.Private.CoreLib/*
    exclude:
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT
    - src/installer/*
    - src/libraries/*
    - eng/pipelines/installer/*
    - eng/pipelines/libraries/*


pr: none

jobs:
#
# Checkout repository
#
- template: /eng/pipelines/common/checkout-job.yml

#
# Release builds
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/coreclr/templates/build-job.yml
    buildConfig: release
    platformGroup: all
    jobParameters:
      timeoutInMinutes: 120

#
# Release test builds
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/coreclr/templates/build-test-job.yml
    buildConfig: release
    platformGroup: all
    testGroup: outerloop

#
# Release test runs
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/coreclr/templates/run-test-job.yml
    buildConfig: release
    platformGroup: all
    helixQueueGroup: ci
    helixQueuesTemplate: /eng/pipelines/coreclr/templates/helix-queues-setup.yml
    jobParameters:
      testGroup: outerloop

#
# Release R2R test runs
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/coreclr/templates/run-test-job.yml
    buildConfig: release
    platformGroup: all
    helixQueueGroup: ci
    helixQueuesTemplate: /eng/pipelines/coreclr/templates/helix-queues-setup.yml
    jobParameters:
      testGroup: outerloop
      readyToRun: true
      displayNameArgs: R2R


#
# Crossgen-comparison jobs
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/coreclr/templates/crossgen-comparison-job.yml
    buildConfig: release
    platforms:
    - Linux_arm
    helixQueueGroup: ci
    helixQueuesTemplate: /eng/pipelines/coreclr/templates/helix-queues-setup.yml
